### ISSUE TITLE
Get error when I set fields as tuples instead of lists

### ISSUE THREAD

**Issue by theosotr** [pyeve/cerberus#271]
I have the following piece of code.

``` python
from cerberus import Validator


schema = {
    'my_field': {
        'type': 'list',
        'schema': {'type': 'string'}
    }
}

validator = Validator(schema)

data = {'my_field': ('foo', 'bar')}

validator.validate(data)
```

I get the following exception:
`TypeError: 'tuple' object does not support item assignment`

When I set `my_field` as list works fine. However, I would like cerberus to support `tuple objects` as well.

**Comment by funkyfuture** [comment]
could you please provide the full traceback?!

**Comment by andreymal** [comment]
I'm not author, but i could:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andreymal/.local/lib/python3.5/site-packages/cerberus/validator.py", line 739, in validate
    self.__normalize_mapping(self.document, self.schema)
  File "/home/andreymal/.local/lib/python3.5/site-packages/cerberus/validator.py", line 499, in __normalize_mapping
    self.__normalize_containers(mapping, schema)
  File "/home/andreymal/.local/lib/python3.5/site-packages/cerberus/validator.py", line 564, in __normalize_containers
    self.__normalize_sequence(field, mapping, schema)
  File "/home/andreymal/.local/lib/python3.5/site-packages/cerberus/validator.py", line 620, in __normalize_sequence
    mapping[field][i] = result[i]
TypeError: 'tuple' object does not support item assignment
```

-------

Generally, Cerberus modifies input, i think this is very bad:

```python
original = [1, 2]

schema = {
    'my_field': {'type': 'list', 'schema': {'type': 'string', 'coerce': str}}
}

validator = Validator(schema)
validator.validate({'my_field': original})

print(original == [1, 2])  # False — WAT?
print(original == ['1', '2'])  # True — WAAT??!1
```

**Comment by funkyfuture** [comment]
@theosotr support for normalizing tuples would have to be amended. it's certainly welcome. in your case you could also avoid hitting the normalization code by calling `validate` with `normalize=False`.

@andreymal this behavior has recently been amended to the docs.
