### ISSUE TITLE
NotImplementedError when accessing validator errors while using anyof list of dict

### ISSUE THREAD

**Issue by mattskone** [pyeve/cerberus#356]
Using Cerberus 1.1

I consulted available documentation and found nothing relevant to this problem.  It seems similar to #299, but I'm adding this issue to document alternative repro steps, as they are not the same here as in #299 (using `anyof` instead of `oneof`).  Feel free to close this issue if the pending fix in https://github.com/pyeve/cerberus/commit/c21aac1e9f07551122c2540654bbbdc23452ec4d also fixes this issue.

#### Use-case abstract

I have a schema that specifies one element, a dictionary which should be valid if it conforms to any of a list of additional "sub-schemas".

----

#### Support request / Bug report

In this example, the "sub-schema" requires a string value, but an integer is used.

```python
from cerberus import Validator

schema = {'foo': {'anyof': [{'type': 'dict', 'schema': {'bar': {'type': 'dict', 'valueschema': {'type': 'string'}}}}]}}
doc = {'foo': {'bar': {'baz': 1}}}
v = Validator()
v.validate(doc, schema)
v.errors
```

Expected behavior: a graceful exit with a Cerberus error message

Actual behavior:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/share/virtualenvs/vcloud-rf72CdgU/lib/python3.6/site-packages/cerberus/validator.py", line 391, in errors
    return self.error_handler(self._errors)
  File "/root/.local/share/virtualenvs/vcloud-rf72CdgU/lib/python3.6/site-packages/cerberus/errors.py", line 473, in __call__
    self.extend(errors)
  File "/root/.local/share/virtualenvs/vcloud-rf72CdgU/lib/python3.6/site-packages/cerberus/errors.py", line 375, in extend
    self.add(error)
  File "/root/.local/share/virtualenvs/vcloud-rf72CdgU/lib/python3.6/site-packages/cerberus/errors.py", line 482, in add
    self.insert_logic_error(error)
  File "/root/.local/share/virtualenvs/vcloud-rf72CdgU/lib/python3.6/site-packages/cerberus/errors.py", line 549, in insert_logic_error
    raise NotImplementedError
NotImplementedError
```

**Comment by funkyfuture** [comment]
i can report that the examples passes with the current `master`'s HEAD commit.

**Comment by radix** [comment]
Is there any hope of a new release of cerberus?

**Comment by bruno-t-de-renzo** [comment]
Having the same here. A new release would be great!
Thanks

**Comment by funkyfuture** [comment]
Cerberus 1.2 was released on April, 12th. if there's still an issue with this, make some noise.
