### ISSUE TITLE
Support for any iterable (instead of just list) in "allowed" rule.

### ISSUE THREAD

**Issue by crunk1** [pyeve/cerberus#384]
Used Cerberus version / latest commit: 1.2
Python version: 3.6.5

- I consulted these documentations:
  - [x] http://docs.python-cerberus.org/en/stable/
  - [x] http://docs.python-cerberus.org/en/latest/

- [x] I found nothing relevant to my problem in the docs.
- [x] I found the documentation not helpful to my problem.

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

----

#### Use-case abstract

I suggest adding support for using iterables in the "allowed" validation rule. In particular, I have a string enum class derived from enum.Enum. An enum.Enum is iterable. I'll try to demonstrate my use case:
```python3
class MyEnum(StrEnum):
  FOO = 'FOO'

# Behavior of MyEnum
# list(MyEnum)         -> [<MyEnum.FOO: 'FOO'>]
# 'FOO' in MyEnum      -> True
# 'BAR' in MyEnum      -> False
# MyEnum.FOO in MyEnum -> True
# MyEnum.FOO == 'FOO'  -> True
# MyEnum.FOO == 'BAR'  -> False

# This works, but is undesirable:
schema = {
  'foo': {'type': 'list', 'allowed': list(MyEnum)},
}
v = cerberus.Validator(schema)
# v.validate({'foo': [MyEnum.FOO, 'FOO']}) -> True

# This raises an error:
schema = {
  'foo': {'type': 'list', 'allowed': MyEnum},
}
v = cerberus.Validator(schema)
# Traceback (most recent call last):
#   File "<input>", line 1, in <module>
#   File "C:\Python36\lib\site-packages\cerberus\validator.py", line 169, in __init__
#     self.schema = kwargs.get('schema', None)
#   File "C:\Python36\lib\site-packages\cerberus\validator.py", line 509, in schema
#     self._schema = DefinitionSchema(self, schema)
#   File "C:\Python36\lib\site-packages\cerberus\schema.py", line 69, in __init__
#     self.validate(schema)
#   File "C:\Python36\lib\site-packages\cerberus\schema.py", line 197, in validate
#     self._validate(schema)
#   File "C:\Python36\lib\site-packages\cerberus\schema.py", line 219, in _validate
#     raise SchemaError(self.schema_validator.errors)
# cerberus.schema.SchemaError: {'foo': [{'allowed': ['must be of list type']}]}
```

**Comment by funkyfuture** [comment]
afaict, supporting this would just require to change the [rule's constraint schema](https://github.com/pyeve/cerberus/blob/fd65f470286109f5d9ac29e26f12dcffdc6b15bd/cerberus/validator.py#L958) to `'type.collections.Container`. therefore the schema validator would need a type definition for that. that shouldn't be too tricky once you wrapped your head around the schema validation mechanics.

**Comment by crunk1** [comment]
Mind filling me in on the mechanics? I've been looking for usages of _validate_allowed and can't see where it is used.

**Comment by crunk1** [comment]
Nvm, think I found it :)
