### ISSUE TITLE
about JSONErrorHandler error

### ISSUE THREAD

**Issue by xiaoyezi2004** [pyeve/cerberus#430]
is JSONErrorHandler implemented?

After reading the article : http://cerberus-collections.readthedocs.io/en/latest/error_handlers.html

Here is my simple test code:

```import cerberus
import cerberus_collections

schema = {'name': { "type": "string",
"maxlength": 4
}
}
v = cerberus.validator(schema,error_handler=cerberus_collections.JSONErrorHandler)
v({'name': 'Einhorn'})

with open('errors.json', 'wt') as f:
f.write(v.errors)
```

But I got the error:
```C:\Users\U0145216\git\Python\Scripts\python.exe C:/Users/U0145216/git/test/learning.py
Traceback (most recent call last):
File "C:/Users/U0145216/git/test/learning.py", line 2, in 
import cerberus_collections
File "C:\Users\U0145216\git\Python\lib\site-packages\cerberus_collections_init_.py", line 4, in 
from cerberus_collections.error_handlers import * # noqa: F401, F403
ModuleNotFoundError: No module named 'cerberus_collections.error_handlers'

Process finished with exit code 1
```

I am using Python 3.6.5, cerberus 1.2
after install cerberus-collections, when i use
from cerberus_collections.error_handlers.json import JSONErrorHandler,
I got the error below:
```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from cerberus_collections.error_handlers.json import JSONErrorHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Python\Python36\lib\site-packages\cerberus_collections\__init__.py", line 4, in <module>
    from cerberus_collections.error_handlers import *  # noqa: F401, F403
ModuleNotFoundError: No module named 'cerberus_collections.error_handlers'
>>>
```
And I have asked my fried to try, the same result.
Could anyone please give some advice?
Do i need a higer version of cerberus? I am using 1.2

here is the code in E:\Python\Python36\lib\site-packages\cerberus_collections_init_.py
```
from cerberus.utils import validator_factory  # noqa: F401

from cerberus_collections.error_handlers import *  # noqa: F401, F403
from cerberus_collections.versions import __version__  # noqa: F401

VanillaValidator = Validator = cerberus.Validator
```

**Comment by funkyfuture** [comment]
you have already opended that issue in the proper repository.

please keep in mind that we do all this in our spare time, raising questions in various places won't help and just costs more time. you'd be better off to take your time to debug the issue.
