### ISSUE TITLE
`'allowed'` rules crash when validating against a nested list

### ISSUE THREAD

**Issue by rmarren1** [pyeve/cerberus#437]
Used Cerberus version / latest commit: 1.2

- [ X ] I have the capacity to improve the docs when my problem is solved.
- [ X ] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

#### Bug report / Feature request

`'allowed'` rules crash when validating against a nested list. See below:
```
>>> import cerberus
>>> v = cerberus.Validator({'val': {'allowed': ['one', 'two', 'three']}})
>>> v.validate({'val': [[]]})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ryan/.local/share/virtualenvs/validate/local/lib/python2.7/site-packages/cerberus/validator.py", line 877, in validate
    self.__validate_definitions(definitions, field)
  File "/home/ryan/.local/share/virtualenvs/validate/local/lib/python2.7/site-packages/cerberus/validator.py", line 940, in __validate_definitions
    result = validate_rule(rule)
  File "/home/ryan/.local/share/virtualenvs/validate/local/lib/python2.7/site-packages/cerberus/validator.py", line 922, in validate_rule
    return validator(definitions.get(rule, None), field, value)
  File "/home/ryan/.local/share/virtualenvs/validate/local/lib/python2.7/site-packages/cerberus/validator.py", line 960, in _validate_allowed
    unallowed = set(value) - set(allowed_values)

```

**Comment by funkyfuture** [comment]
i see the referenced issue, but can you please give a short summary of the intended use-case?

my first suggestion would be to restrict the field's type to a hashable one.

**Comment by rmarren1** [comment]
I am trying to generate a schema for `a string, number, boolean, Component, or None, or a list of those` where `Component` is an instance of a class.

For example,
* `None`
* 'hi'
* `[None, 'hi']`

should all be accepted.

This is the schema I would like to use:
```
{
    'children': {
        'nullable': True,
        'anyof': [
            {'type': 'string'},
            {'type': 'number'},
            {'type': 'boolean'},
            {'type': 'component'},
            {'nullable': True, 'allowed': [None]},
            {'schema': {
                'nullable': True,
                'anyof': [
                    {'type': 'string'},
                    {'type': 'number'},
                    {'type': 'boolean'},
                    {'type': 'component'},
                    {'nullable': True, 'allowed': [None]}]},
                'type': 'list'}
         ]}
```

Basically, I am having trouble adding `None` to the `anyof` list.
