### ISSUE TITLE
Unexpected TypeError raised on validation when using schema_registry and a list is passed instead of single value

### ISSUE THREAD

**Issue by alexandrefvb** [pyeve/cerberus#458]
Used Cerberus version: 1.2

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [x] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

Using schema_registry to define schemas of models with references between schemas.

----

#### Bug report / Feature request

A unexpected TypeError is raised on this scenario:

1. Define two schemas 'A' and 'B' on schema registry with 'A' referencing 'B' on a single value attribute
2. Create a validator with schema 'A'
3. Call validation method passing b value as a list

```
>>> from cerberus import schema_registry, Validator
>>> schema_registry.add('A', { 'b': { 'schema': 'B' } })
>>> schema_registry.add('B', { 'c': { 'type': 'string' } })
>>> v = Validator('A')
>>> v.validated({'b':{'c':'d'}})
{'b': {'c': 'd'}}
>>> v.validated({'b':[{'c':'d'}]})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fidelis/workspaces/yandeh/b2b/b2b-api/venv/lib/python3.6/site-packages/cerberus/validator.py", line 895, in validated
    self.validate(*args, **kwargs)
  File "/home/fidelis/workspaces/yandeh/b2b/b2b-api/venv/lib/python3.6/site-packages/cerberus/validator.py", line 870, in validate
    self.__normalize_mapping(self.document, self.schema)
  File "/home/fidelis/workspaces/yandeh/b2b/b2b-api/venv/lib/python3.6/site-packages/cerberus/validator.py", line 617, in __normalize_mapping
    self.__normalize_containers(mapping, schema)
  File "/home/fidelis/workspaces/yandeh/b2b/b2b-api/venv/lib/python3.6/site-packages/cerberus/validator.py", line 687, in __normalize_containers
    self.__normalize_sequence(field, mapping, schema)
  File "/home/fidelis/workspaces/yandeh/b2b/b2b-api/venv/lib/python3.6/site-packages/cerberus/validator.py", line 744, in __normalize_sequence
    result = validator.normalized(document, always_return_document=True)
  File "/home/fidelis/workspaces/yandeh/b2b/b2b-api/venv/lib/python3.6/site-packages/cerberus/validator.py", line 594, in normalized
    self.__normalize_mapping(self.document, self.schema)
  File "/home/fidelis/workspaces/yandeh/b2b/b2b-api/venv/lib/python3.6/site-packages/cerberus/validator.py", line 608, in __normalize_mapping
    self.__normalize_rename_fields(mapping, schema)
  File "/home/fidelis/workspaces/yandeh/b2b/b2b-api/venv/lib/python3.6/site-packages/cerberus/validator.py", line 761, in __normalize_rename_fields
    self._normalize_rename(mapping, schema, field)
  File "/home/fidelis/workspaces/yandeh/b2b/b2b-api/venv/lib/python3.6/site-packages/cerberus/validator.py", line 771, in _normalize_rename
    if 'rename' in schema[field]:
TypeError: argument of type 'NoneType' is not iterable

```
----

#### Proposed solution

Change _resolve_rules_set method of cerberus.Validator class from:

```
    def _resolve_rules_set(self, rules_set):
        if isinstance(rules_set, Mapping):
            return rules_set
        elif isinstance(rules_set, _str_type):
            return self.rules_set_registry.get(rules_set)
        return None
```

to:

```
    def _resolve_rules_set(self, rules_set):
        if isinstance(rules_set, Mapping):
            return rules_set
        elif isinstance(rules_set, _str_type):
            return self.rules_set_registry.get(rules_set, {})
        return None
```

**Comment by alexandrefvb** [comment]
the class to apply the fix is cerberus.BareValidator

**Comment by funkyfuture** [comment]
i doubt that the error arises from the registry implementation - returning `None` for a non-existing entry is the right thing to do, but i suspect the error to be in the normalization code. have you tried what happens when you add a `type` rule with `list` as constraint beside the `schema` rule?

**Comment by NMisko** [comment]
minimal example: 
```
from cerberus import Validator, schema_registry
 
schema_registry.add("registered_schema", {})
schema = {"field": {"type": "dict", "schema": "registered_schema"}}
validator = Validator(schema)
validator.validate({"field": [{}]})
```
-> `TypeError`
@alexandrefvb did you do anything more here?

**Comment by alexandrefvb** [comment]
Hi @NMisko,

In my project I decided to subclass Validator and replace _resolve_rules_set method as stated in proposed solution. As @funkyfuture stated this solution is not the best, but for my project it works well and not caused any unexpected behavior in my usecases. A better solution is trace all points affected by the bug and change them to validate if None was returned by schema registry but there are many places on code affected so I decided to use this simple solution.

As reference I did: 
```
import cerberus

class Validator(cerberus.Validator):
    def _resolve_rules_set(self, rules_set):
        if isinstance(rules_set, Mapping):
            return rules_set
        elif isinstance(rules_set, _str_type):
            return self.rules_set_registry.get(rules_set, {})
        return None
```
and used this custom Validator class to validate the schemas.

**Comment by NMisko** [comment]
Thanks a lot, I wanted to see if I could help out here, but it seems to be a little too complicated for me to fix.
