### ISSUE TITLE
Set __version__ to an invalid value if package distribution is not found

### ISSUE THREAD

**Issue by s4heid** [pyeve/cerberus#471]
Used Cerberus version / latest commit: master

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [x] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

When attempting to use the cerberus repo as a git submodule in a project, users are going to get a `DistributionNotFound` error, because the [get_distribution()](https://github.com/pyeve/cerberus/blob/f4b78f8a9002b6464eaf1a5ee714986621be3497/cerberus/__init__.py) method in the `__init__.py` file cannot retrieve the distribution of the package.

See stack trace:

```
Traceback (most recent call last):
...
    from cerberus import Validator
  File "/Users/s4heid/workspace/some-project/lib/cerberus/cerberus/__init__.py", line 24, in <module>
    __version__ = pkg_resources.get_distribution('Cerberus').version
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Cerberus' distribution was not found and is required by the application
```

I currently workaround this issue by manually setting `__version__` to some string.

----

#### Bug report / Feature request

I would expect that if `pkg_resources.DistributionNotFound` is raised, the exception is getting catched and `__version__` set to an invalid version string which won't break your source installation and at the same time indicate that something is broken if the distribution cannot be found.

The  name of the version string could be something like `unknown`, which I've seen in other projects as well.

**Comment by funkyfuture** [comment]
would `not installed` be feasible as replacement or is it too confusing? `unknown` is okay too. go for it!

i wouldn't consider it as a bug, as you can help yourself easily in the situation you describe. nonetheless we should backport it then.

**Comment by s4heid** [comment]
Hi @funkyfuture,

thanks for your feedback, I’ll make a pull request in a bit.

Regarding the usage of `not installed`, I think this would be a good option. My only concern is the whitespace, which seems a bit confusing for a version string. Since we wouldn’t be conform to the canonical format of [PEP440](https://www.python.org/dev/peps/pep-0440) anyway, it probably doesn’t matter too much.

However, I’d be tempted to stick with `unknown` for now, for the simple reason that it keeps consistency with other packages such as [pyscaffold](https://github.com/pyscaffold/pyscaffold/blob/feb1042473ec14200c780ff5d144c840dd0856fe/src/pyscaffold/__init__.py#L7). 

Does this make sense for you?

**Comment by funkyfuture** [comment]
yep
