### ISSUE TITLE
setuptools should be in the requirements list

### ISSUE THREAD

**Issue by Innuendo1975** [pyeve/cerberus#499]
Hello,

on my minimized docker environment with no pip installed I have the following exception traceback:

```
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cerberus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/vendor/cerberus/__init__.py", line 13, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ImportError: No module named 'pkg_resources'
```

Indeed I can solve it by installing setuptools but it should be included in **install_requires** list of setup.py

**Comment by funkyfuture** [comment]
Thanks for reporting! A fix will be available with the `1.3.2` release.
