### ISSUE TITLE
Unable to expand schema_registry

### ISSUE THREAD

**Issue by vkropotko** [pyeve/cerberus#502]
cerberus version: 1.3.1, python version 3.7

When I try to add to schema_registry I get an error - 'not iterable':
```>>> from cerberus import schema_registry
>>> custom_schema = (('id', {'type': 'integer', 'coerce': int, 'min': 1}))
>>> schema_registry.add(*custom_schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vkropotko/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cerberus/schema.py", line 483, in add
    self._storage[name] = self._expand_definition(definition)
  File "/Users/vkropotko/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cerberus/schema.py", line 524, in _expand_definition
    return DefinitionSchema.expand(definition)
  File "/Users/vkropotko/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cerberus/schema.py", line 128, in expand
    schema = cls._rename_deprecated_rulenames(schema)
  File "/Users/vkropotko/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cerberus/schema.py", line 225, in _rename_deprecated_rulenames
    if old not in rules:
TypeError: argument of type 'type' is not iterable```
```
It can be fixed here:
https://github.com/pyeve/cerberus/blob/master/cerberus/schema.py#L216
with:
```
from collections.abc import Iterable
if isinstance(rules, str) or not isinstance(rules, Iterable):
    continue
```
But I'm not pretty sure that it's a bug. =)

**Comment by funkyfuture** [comment]
no, it's not a bug.

you're either missing the wrapping field or you should add the rule set to the a `RulesSetRegistry` instance. in other words: the second argument you pass is a rules set, but not an expected schema.
