### ISSUE TITLE
pip install cerberus ERROR

### ISSUE THREAD

**Issue by Alexmhack** [pyeve/cerberus#574]
Great work on the module!!, nice features and nice documentation which is much better when comparing with `jsonschema`'s very confusing and not that much good features.

I tried installing the module using the plain old `pip install` on Ubuntu 20 using Python3.8.5 and got stuck with the error mentioned in the stack trace below. Would really appreciate the help, Thanks!!.

```
(venv3) User~xxx$ pip install cerberus
Collecting cerberus
  Using cached Cerberus-1.3.4.tar.gz (63 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: xxx/project_dir/venv3/bin/python3 xxx/project_dir/venv3/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-p2kj9t3k/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "xxx/project_dir/venv3/lib/python3.8/site-packages/pip/__main__.py", line 19, in <module>
      sys.exit(_main())
    File "xxx/project_dir/venv3/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "xxx/project_dir/venv3/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
      module = importlib.import_module(module_path)
    File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "xxx/project_dir/venv3/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand
    File "xxx/project_dir/venv3/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 21, in <module>
      from pip._internal.req.constructors import (
    File "xxx/project_dir/venv3/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 11, in <module>
      from .req_file import parse_requirements
    File "xxx/project_dir/venv3/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 25, in <module>
      from pip._internal.req.constructors import (
    File "xxx/project_dir/venv3/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 28, in <module>
      from pip._internal.req.req_install import InstallRequirement
    File "xxx/project_dir/venv3/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 17, in <module>
      from pip._vendor.pep517.wrappers import Pep517HookCaller
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/wrappers.py", line 14, in <module>
    File "/usr/lib/python3.8/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "xxx/project_dir/venv3/lib/python3.8/site-packages/typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "xxx/project_dir/venv3/lib/python3.8/site-packages/typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: xxx/project_dir/venv3/bin/python3 xxx/project_dir/venv3/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-p2kj9t3k/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Comment by funkyfuture** [comment]
this looks like an issue with the Python interpreter you're using. i can't reproduce this in fresh environments.
